# Generated by Django 5.1.2 on 2024-10-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['time_create'], 'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='time_created',
            new_name='time_create',
        ),
    ]
