# Generated by Django 5.1.2 on 2024-11-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'роль', 'verbose_name_plural': 'роли'},
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/members/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, verbose_name='био'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.role', verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
    ]
